# Code_Book

## Subject

The ID of people under study - integers 1-30

## Activity

The activity they were performing when the measurement was taken :

1 WALKING

2 WALKING_UPSTAIRS

3 WALKING_DOWNSTAIRS

4 SITTING

5 STANDING

6 LAYING

##  Features

Mean and standard deviations were calculated for all features.
mean(): Mean value
std(): Standard deviation


'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions

### accelerometer and gyroscope data 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ(prefix 't' to denote time) 

*tBodyAccMeanX

*tBodyAccMeanY

*tBodyAccMeanZ

*tBodyAccStdX

*tBodyAccStdY

*tBodyAccStdZ

*tBodyGyroMeanX

*tBodyGyroMeanY

*tBodyGyroMeanZ

*tBodyGyroStdX

*tBodyGyroStdY

*tBodyGyroStdZ

### Data about jerk (keyword = jerk)

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ

*tBodyAccJerkMeanX

*tBodyAccJerkMeanY

*tBodyAccJerkMeanZ

*tBodyAccJerkStdX

*tBodyAccJerkStdY

*tBodyAccJerkStdZ


*tBodyGyroJerkMeanX

*tBodyGyroJerkMeanY

*tBodyGyroJerkMeanZ

*tBodyGyroJerkStdX

*tBodyGyroJerkStdY

*tBodyGyroJerkStdZ



### Magnitude by eucledian norm (keyword = mag)

magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag)


*tBodyAccMagMean

*tBodyAccMagStd

*tGravityAccMagMean

*tGravityAccMagStd

*tBodyAccJerkMagMean

*tBodyAccJerkMagStd

*tBodyGyroMagMean

*tBodyGyroMagStd

*tBodyGyroJerkMagMean

*tBodyGyroJerkMagStd


### Corresponding fourier transform (key = starts with f)

Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

*fBodyAccMeanX

*fBodyAccMeanY

*fBodyAccMeanZ

*fBodyAccStdX

*fBodyAccStdY

*fBodyAccStdZ

*fBodyAccMeanFreqX

*fBodyAccMeanFreqY

*fBodyAccMeanFreqZ

*fBodyAccJerkMeanX

*fBodyAccJerkMeanY

*fBodyAccJerkMeanZ

*fBodyAccJerkStdX

*fBodyAccJerkStdY

*fBodyAccJerkStdZ

*fBodyAccJerkMeanFreqX

*fBodyAccJerkMeanFreqY

*fBodyAccJerkMeanFreqZ

*fBodyGyroMeanX

*fBodyGyroMeanY

*fBodyGyroMeanZ

*fBodyGyroStdX

*fBodyGyroStdY

*fBodyGyroStdZ

*fBodyGyroMeanFreqX

*fBodyGyroMeanFreqY

*fBodyGyroMeanFreqZ

*fBodyAccMagMean

*fBodyAccMagStd

*fBodyAccMagMeanFreq

*fBodyBodyAccJerkMagMean

*fBodyBodyAccJerkMagStd

*fBodyBodyAccJerkMagMeanFreq

*fBodyBodyGyroMagMean

*fBodyBodyGyroMagStd

*fBodyBodyGyroMagMeanFreq

*fBodyBodyGyroJerkMagMean

*fBodyBodyGyroJerkMagStd

*fBodyBodyGyroJerkMagMeanFreq

